[profile.default]
src = 'contracts'
test = 'foundry/test'
libs = ['foundry/lib']
solc_version = '0.8.24'
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 120
multiline_func_header = 'params_first'

